spring:
  datasource:
    url: jdbc:h2:mem:recordstore;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  swagger-ui:
    path: /swagger
